export const Activities = {
    AmericanFootball: 'Football',
    Archery: 'Archery',
    AustralianFootball: 'AUS Football',
    Badminton: 'Badminton',
    Baseball: 'Baseball',
    Basketball: 'Basketball',
    Bowling: 'Bowling',
    Boxing: 'Boxing',
    CardioDance: 'Dance',
    Climbing: 'Climbing',
    Cooldown: 'Cool down',
    Cricket: 'Cricket',
    CrossTraining: 'XTraining',
    Curling: 'Curling',
    Cycling: 'Cycling',
    Dance: 'Dance',
    DiscSports: 'Disc Sports',
    Elliptical: 'Elliptical',
    EquestrianSports: 'Equestrian',
    Fencing: 'Fencing',
    FitnessGaming: 'Gaming',
    Fishing: 'Fishing',
    FunctionalStrengthTraining: 'Strength Training',
    Golf: 'Golf',
    Gymnastics: 'Gymnastics',
    Handball: 'Handball',
    Hiking: 'Hiking',
    Hockey: 'Hockey',
    Hunting: 'Hunting',
    Lacrosse: 'Lacrosse',
    MartialArts: 'Martial Arts',
    MindAndBody: 'Mind & Body',
    PaddleSports: 'Paddle Sports',
    Play: 'Play',
    Pickleball: 'Pickleball',
    PreparationAndRecovery: 'Recovery',
    Racquetball: 'Racquetball',
    Rowing: 'Rowing',
    Rugby: 'Rugby',
    Running: 'Running',
    Sailing: 'Sailing',
    SkatingSports: 'Skating',
    SnowSports: 'Snow Sports',
    Soccer: 'Soccer',
    SocialDance: 'Dance',
    Softball: 'Softball',
    Squash: 'Squash',
    StairClimbing: 'Stairs',
    SurfingSports: 'Surfing',
    Swimming: 'Swimming',
    TableTennis: 'Table Tennis',
    Tennis: 'Tennis',
    TrackAndField: 'Track&Field',
    TraditionalStrengthTraining: 'Strength Training',
    Volleyball: 'Volleyball',
    Walking: 'Walking',
    WaterFitness: 'Water Fitness',
    WaterPolo: 'WaterPolo',
    WaterSports: 'Water Sports',
    Wrestling: 'Wrestling',
    Yoga: 'Yoga',
    Barre: 'Barre',
    CoreTraining: 'Core',
    CrossCountrySkiing: 'XCountry Skiing',
    DownhillSkiing: 'Skiing',
    Flexibility: 'Flexibility',
    HighIntensityIntervalTraining: 'HIT',
    JumpRope: 'Jump Rope',
    Kickboxing: 'Kickboxing',
    Pilates: 'Pilates',
    Snowboarding: 'Snowboarding',
    Stairs: 'Stairs',
    StepTraining: 'Steps',
    WheelchairWalkPace: 'WheelchairWalkPace',
    WheelchairRunPace: 'WheelchairRunPace',
    TaiChi: 'TaiChi',
    MixedCardio: 'Mixed Cardio',
    HandCycling: 'Hand Cycling',
  }