export const Activities = {
    AmericanFootball: 'Football',
    Archery: 'Archery',
    AustralianFootball: 'AUS Football',
    Badminton: 'Badminton',
    Baseball: 'Baseball',
    Basketball: 'Basketball',
    Bowling: 'Bowling',
    Boxing: 'Boxing',
    CardioDance: 'Dance',
    Climbing: 'Climbing',
    Cooldown: 'Cool down',
    Cricket: 'Cricket',
    CrossTraining: 'XTraining',
    Curling: 'Curling',
    Cycling: 'Cycling',
    Dance: 'Dance',
    DiscSports: 'Disc Sports',
    Elliptical: 'Elliptical',
    EquestrianSports: 'Equestrian',
    Fencing: 'Fencing',
    FitnessGaming: 'Gaming',
    Fishing: 'Fishing',
    FunctionalStrengthTraining: 'Strength Training',
    Golf: 'Golf',
    Gymnastics: 'Gymnastics',
    Handball: 'Handball',
    Hiking: 'Hiking',
    Hockey: 'Hockey',
    Hunting: 'Hunting',
    Lacrosse: 'Lacrosse',
    MartialArts: 'Martial Arts',
    MindAndBody: 'Mind & Body',
    PaddleSports: 'Paddle Sports',
    Play: 'Play',
    Pickleball: 'Pickleball',
    PreparationAndRecovery: 'Recovery',
    Racquetball: 'Racquetball',
    Rowing: 'Rowing',
    Rugby: 'Rugby',
    Running: 'Running',
    Sailing: 'Sailing',
    SkatingSports: 'Skating',
    SnowSports: 'Snow Sports',
    Soccer: 'Soccer',
    SocialDance: 'Dance',
    Softball: 'Softball',
    Squash: 'Squash',
    StairClimbing: 'Stairs',
    SurfingSports: 'Surfing',
    Swimming: 'Swimming',
    TableTennis: 'Table Tennis',
    Tennis: 'Tennis',
    TrackAndField: 'Track&Field',
    TraditionalStrengthTraining: 'Strength Training',
    Volleyball: 'Volleyball',
    Walking: 'Walking',
    WaterFitness: 'Water Fitness',
    WaterPolo: 'WaterPolo',
    WaterSports: 'Water Sports',
    Wrestling: 'Wrestling',
    Yoga: 'Yoga',
    Barre: 'Barre',
    CoreTraining: 'Core',
    CrossCountrySkiing: 'XCountry Skiing',
    DownhillSkiing: 'Skiing',
    Flexibility: 'Flexibility',
    HighIntensityIntervalTraining: 'HIT',
    JumpRope: 'Jump Rope',
    Kickboxing: 'Kickboxing',
    Pilates: 'Pilates',
    Snowboarding: 'Snowboarding',
    Stairs: 'Stairs',
    StepTraining: 'Steps',
    WheelchairWalkPace: 'WheelchairWalkPace',
    WheelchairRunPace: 'WheelchairRunPace',
    TaiChi: 'TaiChi',
    MixedCardio: 'Mixed Cardio',
    HandCycling: 'Hand Cycling',
  }

  export const Activity_Colors = {
    AmericanFootball: '#f97316',
    Archery: '#f59e0b',
    AustralianFootball: '#eab308',
    Badminton: '#84cc16',
    Baseball: '#22c55e',
    Basketball: '#14b8a6',
    Bowling: '#0891b2',
    Boxing: '#0284c7',
    CardioDance: '#3b82f6',
    Climbing: '#4f46e5',
    Cooldown: '#8b5cf6',
    Cricket: '#a855f7',
    CrossTraining: '#ec4899',
    Curling: '#f43f5e',
    Cycling: '#fdba74',
    Dance: '#fcd34d',
    DiscSports: '#fde047',
    Elliptical: '#86efac',
    EquestrianSports: '#4ade80',
    Fencing: '#2dd4bf',
    FitnessGaming: '#22d3ee',
    Fishing: '#38bdf8',
    FunctionalStrengthTraining: '#60a5fa',
    Golf: '#818cf8',
    Gymnastics: '#a78bfa',
    Handball: '#c084fc',
    Hiking: '#e879f9',
    Hockey: '#f472b6',
    Hunting: '#fb7185',
    Lacrosse: '#fda4af',
    MartialArts: '#ff6b6b',
    MindAndBody: '#feca57',
    PaddleSports: '#ff9ff3',
    Play: '#54a0ff',
    Pickleball: '#5f27cd',
    PreparationAndRecovery: '#48dbfb',
    Racquetball: '#ff6b6b',
    Rowing: '#ff9ff3',
    Rugby: '#54a0ff',
    Running: '#5f27cd',
    Sailing: '#48dbfb',
    SkatingSports: '#ff6b6b',
    SnowSports: '#ff9ff3',
    Soccer: '#54a0ff',
    SocialDance: '#5f27cd',
    Softball: '#48dbfb',
    Squash: '#ff6b6b',
    StairClimbing: '#ff9ff3',
    SurfingSports: '#54a0ff',
    Swimming: '#5f27cd',
    TableTennis: '#48dbfb',
    Tennis: '#ff6b6b',
    TrackAndField: '#ff9ff3',
    TraditionalStrengthTraining: '#54a0ff',
    Volleyball: '#5f27cd',
    Walking: '#48dbfb',
    WaterFitness: '#ff6b6b',
    WaterPolo: '#ff9ff3',
    WaterSports: '#54a0ff',
    Wrestling: '#5f27cd',
    Yoga: '#48dbfb',
    Barre: '#ff6b6b',
    CoreTraining: '#ff9ff3',
    CrossCountrySkiing: '#54a0ff',
    DownhillSkiing: '#5f27cd',
    Flexibility: '#48dbfb',
    HighIntensityIntervalTraining: '#ff6b6b',
    JumpRope: '#ff9ff3',
    Kickboxing: '#54a0ff',
    Pilates: '#5f27cd',
    Snowboarding: '#48dbfb',
    Stairs: '#ff6b6b',
    StepTraining: '#ff9ff3',
    WheelchairWalkPace: '#54a0ff',
    WheelchairRunPace: '#5f27cd',
    TaiChi: '#48dbfb',
    MixedCardio: '#ff6b6b',
    HandCycling: '#ff9ff3'
};
